### ISSUE TITLE
Sei-docker monta imagens com o make up, mas não acessa a página de login

### ISSUE THREAD

**Issue by xtremearts** [spbgovbr/sei-docker#80]
Ao configurar o diretório com o código do Sei e rodar o comando make up, todas as imagens sobem corretamente, porém não consegue acessar a página de login conforme abaixo:

Recreating smtp      ... done
Recreating memcached ... done
Recreating mysql     ... done
Recreating solr      ... done
Recreating jod       ... done
Recreating httpd     ... done
make check-sei-isalive
make[1]: Entrando no diretório '/home/tiago/dev/sei-3/sei-docker/dev'

Vamos tentar acessar a pagina de login do SEI, vamos aguardar por 45 segs.
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Aguardando resposta ...
make[1]: Saindo do diretório '/home/tiago/dev/sei-3/sei-docker/dev'

Alguém sabe me dizer o que fiz de errado?

![Captura de tela de 2024-04-08 23-38-03](https://github.com/spbgovbr/sei-docker/assets/35545475/2cf5b5af-664f-4a6f-a0ef-6d132b030cc7)

**Comment by Larvin-Vinicius** [comment]
@xtremearts Se você ainda estiver com o problema, adiciona aqui o seu arquivo envlocal.env

**Comment by marlinhares** [comment]
Olá @xtremearts lembrando que a pasta dev é para desenvolvedor. Caso queira por exemplo debugar o fonte. Caso queira subir um ambiente para teste, demonstração ou treinamento use a pasta infra.

Como informou acima o @Larvin-Vinicius precisamos de mais informações para tentar ajudar. O que vc rodou antes? Como vc posicionou os fontes do SEI antes de rodar? 


Em todo caso subi aqui localmente agora usando a pasta dev e subiu sem nenhum problema.
Segue meu history com o q fiz. Note q eu limpei o docker para garantir q n tinha nenhuma imagem:

```
5752  docker system prune -a
 5753  docker volume prune
 5754  ls

# vou clonar o fonte do SEI e usa-lo mais a frente

 5755  cd ~/projetos/github/pengovbr/sei
 5756  ls
 5757  git checkout 4.0.11
 5758  ls
 5759  mkdir ~/sei/myfontes
 5760  cp -R * ~/sei/myfontes
 5761  cd ~/projetos/github/spbgovbr/sei-docker/dev
 5762  ls

# vou criar o arquivo de config, para o mysql

 5763  make config
 5764  cat .env
 5765  ls
 5766  vim env.env
 5767  ls -la
 5768  cat env
 5769  cat env.env
 5770  cat docker-compose.yml
 5771  make up

# ao rodar o make up ele reclamou q n tinha mapeado a variavel SEI_PATH para os fontes, portanto abaixo fiz o mapeamento

 5772  ls ~/sei/myfontes
 5773  export export SEI_PATH= ~/sei/myfontes
 5774  export export SEI_PATH=~/sei/myfontes
 5775  make up

```

o make up acima respondeu com:
```
Creating mysql     ... done
Creating solr      ... done
Creating jod       ... done
Creating smtp      ... done
Creating memcached ... done
Creating httpd     ... done
make check-sei-isalive
make[1]: Entering directory '/home/marcelo/projetos/github/spbgovbr/sei-docker/dev'

Vamos tentar acessar a pagina de login do SEI, vamos aguardar por 45 segs.
Tentando acessar...
Aguardando resposta ...
Tentando acessar...
Pagina respondeu com tela de login
Acesse com http://localhost:8000/sei ou http://localhost:8000/sip
make[1]: Leaving directory '/home/marcelo/projetos/github/spbgovbr/sei-docker/dev'
```

E ao acessar o http://localhost:8000/sei  abriu normal e consegui logar sem problema

**Comment by xtremearts** [comment]
@marlinhares  obrigado pelo retorno!
Como vou precisar fazer uma personalização em um módulo que é integrado com o Sei utilizei a pasta /dev para subir.

Como me enviaram o código fonte do sei via arquivo zip e não por repositório suspeitei que poderia estar faltando algum arquivo ou algo do tipo, então fiz o seguinte:

renomeei o arquivo env.evn para .env e executei o comando docker-compose up diretamente.

Retornou o seguinte erro:

httpd        | #0 /opt/sip/web/Sip.php(16): require_once()
httpd        | #1 Command line code(2): require_once('/opt/sip/web/Si...')
httpd        | #2 {main}
httpd        |   thrown in /opt/sip/config/ConfiguracaoSip.php on line 3
httpd        | 
httpd        | Fatal error: Uncaught Error: Class 'InfraConfiguracao' not found in /opt/sip/config/ConfiguracaoSip.php:3
httpd        | Stack trace:
httpd        | #0 /opt/sip/web/Sip.php(16): require_once()
httpd        | #1 Command line code(2): require_once('/opt/sip/web/Si...')
httpd        | #2 {main}
httpd        |   thrown in /opt/sip/config/ConfiguracaoSip.php on line 3


Acredito que esse foi o motivo de não subir corretamente com o make up, pois está faltando no código fonte de alguns arquivos de configuração, pois segui os passos corretos para instalação.



@Larvin-Vinicius 
Segue abaixo meu o meu arquivo env.env:

ENVIRONMENT_VERSION=1.14
DOCKER_REGISTRY=processoeletronico
DATABASE_IMAGE=mariadb10.5
DATABASE_TYPE=MySql
DATABASE_HOST=mysql
DATABASE_PORT=3306
DATABASE_DATA_DIR=/var/lib/mysql

SEI_CHAVE_ACESSO=7babf862e12bd48f3101075c399040303d94a493c7ce9306470f719bb453e0428c6135dc
SEI_DATABASE_NAME=sei
SEI_DATABASE_USER=sei_user
SEI_DATABASE_PASSWORD=sei_user
SEI_DATABASE_USER_SCRIPT=sei_user
SEI_DATABASE_PASSWORD_SCRIPT=sei_user

SIP_CHAVE_ACESSO=d27791b894028d9e7fa34887ad6f0c9a2c559cccda5f64f4e108e3573d5db862b66fb933
SIP_DATABASE_NAME=sip
SIP_DATABASE_USER=sip_user
SIP_DATABASE_PASSWORD=sip_user
SIP_DATABASE_USER_SCRIPT=sip_user
SIP_DATABASE_PASSWORD_SCRIPT=sip_user
SEI_PATH=/ ~/home/tiago/dev/sei-codigo

**Comment by marlinhares** [comment]
Olá @xtremearts vc conseguiu subir? n ficou claro pra mim se o problema continua.

**Comment by xtremearts** [comment]
Olá @marlinhares . O problema continua, mas acho que é porque o código do SEI tá incompleto. Me mandaram faltando arquivos, acredito que é por isso que não deu certo com o Make up.

**Comment by marlinhares** [comment]
O SEI_PATH ai no env ta estranho 
SEI_PATH=/ ~/home/tiago/dev/sei-codigo
tem uma barra e um espaço antes do ~
Ajusta ele para o caminho absoluto.

verifique se na pasta /home/tiago/dev/sei-codigo existe 3 diretorios: sei, sip e infra

**Comment by xtremearts** [comment]
@marlinhares . Também tentei colocar o caminho absoluto. Não rodou.
Na minha pasta tem apenas dois diretórios, sei e sip. Provavelmente o código tá incompleto mesmo né? já que não tem essa pasta infra.

Uma dúvida, o código fonte do SEI não está disponível em algum repositório público né?

**Comment by marlinhares** [comment]
Olá @xtremearts sim está incompleto. As pastas são:
- sei
- sip
- infra
  - infra_css (dentro de infra)
  - infra_php (dentro de infra)
  - infra_js (dentro de infra)
 
Outra coisa. Antes de subir remova os arquivos:
sei/config/ConfiguracaoSEI.php
sip/config/ConfiguracaoSip.php

Deixe q estes 2 arquivos serão copiados pelo conteiner automaticamente

**Comment by marlinhares** [comment]
como está há muito tempo sem resposta vou fechar. Caso necessário pode reabrir ifnormando o passo a passo realizado
